// <auto-generated />
using System;
using FCG.Jogos.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FCG.Jogos.Infrastructure.Migrations
{
    [DbContext(typeof(JogosDbContext))]
    partial class JogosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FCG.Jogos.Domain.Jogos.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoAtivacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DataAtivacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JogoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrecoPago")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("FCG.Jogos.Domain.Jogos.Entities.Jogo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("AvaliacaoMedia")
                        .HasColumnType("integer");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<int>("Classificacao")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DataLancamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Desenvolvedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("boolean");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estoque")
                        .HasColumnType("integer");

                    b.Property<string>("ImagemUrl")
                        .HasColumnType("text");

                    b.Property<int>("NumeroAvaliacoes")
                        .HasColumnType("integer");

                    b.Property<string[]>("Plataformas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("Titulo");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("FCG.Jogos.Infrastructure.Jogos.EventSourcing.StoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("AggregateType", "AggregateId");

                    b.ToTable("StoredEvents");
                });

            modelBuilder.Entity("FCG.Jogos.Domain.Jogos.Entities.Compra", b =>
                {
                    b.HasOne("FCG.Jogos.Domain.Jogos.Entities.Jogo", "Jogo")
                        .WithMany("Vendas")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("FCG.Jogos.Domain.Jogos.Entities.Jogo", b =>
                {
                    b.Navigation("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
